server:
  port: 9191
spring:  application:    name: API-GATEWAY  cloud:    gateway:      routes:      - id: MASTERDATA-SERVICE
        uri: lb://masterdata-service
        predicates:            - Path= /olx/masterdata/**
      - id: ADVERTISE-SERVICE
        uri: lb://advertisement-service
        predicates:
            - Path= /olx/adv/** 
      - id: AUTH-SERVICE
        uri: lb://auth-service
        predicates:
            - Path= /olx/auth/**   
  zipkin:
       base-url: http://localhost:9411                      
               
eureka:
  client:
    register-with-eureka: true 
    fetch-registry:  true   
                     